---
- name: test if swap_swappiness is set correctly
  assert:
    that:
      - swap_swappiness is defined
      - swap_swappiness is number
      - swap_swappiness | int >= 0
      - swap_swappiness | int <= 100
    quiet: yes

- name: test if swap_files is set correctly
  assert:
    that:
      - swap_files is iterable
    quiet: yes
  when:
    - swap_files is defined

- name: test if swap_files item is set correctly
  assert:
    that:
      - item.path is defined
      - item.size is number
      - item.size | int >= 0
    quiet: yes
  loop: "{{ swap_files }}"
  loop_control:
    label: "{{ item.path }}"
