---
# tasks file for swap

- name: include assert.yml
  include_tasks: assert.yml
  run_once: yes

- name: set swappiness
  sysctl:
    name: vm.swappiness
    value: "{{ swap_swappiness }}"
    state: present

- block:
    - name: make a swap file
      command: dd if=/dev/zero of={{ item.path }} bs=1048576 count={{ item.size }}
      args:
        creates: "{{ item.path }}"
      loop: "{{ swap_files }}"

    - name: set permission on swap file
      file:
        path: "{{ item.path }}"
        owner: root
        group: root
        mode: "600"
      loop: "{{ swap_files }}"

    - name: make swap file system
      filesystem:
        fstype: swap
        dev: "{{ item.path }}"
      loop: "{{ swap_files }}"

    - name: mount swap
      mount:
        path: none
        src: "{{ item.path }}"
        fstype: swap
        opts: sw
        passno: "0"
        dump: "0"
        state: present
      loop: "{{ swap_files }}"
  when:
    - swap_files is defined
    - swap_files | length > 0
