---
- name: Verify
  hosts: all
  become: yes
  gather_facts: no

  tasks:
    - name: check status of /my.swap
      stat:
        path: /my.swap
      register: swap_my_swap
      failed_when:
        - not swap_my_swap.stat.exists
